
server:
  port: 9000

spring:
  data:
    mongodb:
      port: 27017
      name: sms
      uri: mongodb://localhost:27017/sms

nrs:
  api:
    credentials:
      username: DABMHQ
      password: WTba79'!
    baseurl: https://dashboard.360nrs.com/api/rest
    endpoints:
      sendSms: /sms

mobiweb:
  api:
    credentials:
      username: contact@dabmsarl.com
      password: BD2D3A65