
server:
  port: 9000

spring:
  data:
    mongodb:
      port: 27017
      name: sms
      uri: mongodb://localhost:27017/sms

nrs:
  api:
    credentials:
      username: username
      password: password
    baseurl: url
    endpoints:
      sendSms: /sms

mobiweb:
  api:
    credentials:
      username: username
      password: password
